[package]
name = "modpackr"
version = "0.1.0"
authors = ["Tristan Daniël Maat <tm@tlater.net>"]
edition = "2018"

[workspace]
members = [
    "modpackr-lib"
]

[dependencies]
modpackr-lib = { path = "modpackr-lib" }

console = "0.11.3"
serde_yaml = "0.8.12"
